import type { Metadata } from "next";
import localFont from "next/font/local";
import '@mantine/core/styles.css';
import "./globals.css";
import { theme } from '@/lib/theme';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { Noto_Sans_KR } from 'next/font/google';
import '@mantine/charts/styles.css';

const notoSansKr = Noto_Sans_KR({
  weight: ['300'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "AI-ACS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={notoSansKr.className}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
